#!/usr/bin/env expect

log_user 1

set prompt {/@}
set command_to_test [lindex $argv 0]

# Spawn shell and prepare for consistent output
spawn ksh
send "export PS1='$prompt'\n"
expect $prompt

# Run test completion
puts "--- BEGIN COMPLETION ---"

log_user 0
exp_internal 1
send "${command_to_test}\t"
expect {
    -timeout 3
    -re "${command_to_test}\r\n(.*)\r\n$prompt${command_to_test}" {
        set captured_output $expect_out(1,string)
        puts "==> RESULT:\n\n$captured_output"
    }
    timeout {
        puts "==> TIMEOUT"
    }
}

puts "--- END COMPLETION ---"

send "exit\n"
expect eof
