#!/usr/bin/env expect

log_user 0

set prompt {/@}
set command_to_test [lindex $argv 0]

# Spawn shell and prepare for consistent output
spawn fish -i --private
send "function fish_prompt\n  set_color normal\n  echo -n '$prompt'\nend\n"
expect $prompt

# Run test completion
puts "--- BEGIN COMPLETION ---"

log_user 1
send "${command_to_test}\t\t"
expect {
    -timeout 3
    -re "${command_to_test}\r\n(.*)\r\n$prompt${command_to_test}" {
        set captured_output $expect_out(1,string)
        puts "==> RESULT:\n\n$captured_output"
    }
    timeout {
        puts "==> TIMEOUT"
    }
}

puts "--- END COMPLETION ---"

send "exit\n"
expect eof
