name: Test TabTwo

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
  
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [20] # [16, 18, 19, 20, 21]
        shell: [bash, zsh, fish, ksh, powershell]
        exclude:
          - os: windows-latest
            shell: [bash, zsh, fish, ksh]
      
    env:
      OS: ${{ matrix.os }}
      NODEJS: ${{ matrix.node_version }}
      TEST_OS: ${{ matrix.os == 'windows-latest' && 'win32' || matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'macos-latest' && 'darwin' }}
      TEST_SHELL: ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-npm-${{ hashFiles('package.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.node_version }}-npm
      - name: Install fish
        if: ${{ matrix.shell == 'fish'}}
        uses: fish-actions/install-fish@v1
      - name: Install and test (bash)
        if: ${{ matrix.shell == 'bash'}}
        shell: bash -e {0}
        run: |
          npm install
          npm run test
      - name: Install and test (zsh)
        if: ${{ matrix.shell == 'zsh'}}
        shell: zsh {0}
        run: |
          npm install
          npm run test
      - name: Install and test (fish)
        if: ${{ matrix.shell == 'fish'}}
        shell: fish {0}
        run: |
          npm install
          npm run test
      - name: Install and test (ksh)
        if: ${{ matrix.shell == 'ksh'}}
        shell: ksh {0}
        run: |
          npm install
          npm run test
      - name: Install and test (powershell)
        if: ${{ matrix.shell == 'powershell'}}
        shell: pwsh
        run: |
          npm install
          npm run test


